apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-keeper-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-01
      role: keeper
  template:
    metadata:
      labels:
        app: clickhouse-01
        role: keeper
    spec:
      nodeSelector:
        kubernetes.io/hostname: n4
      volumes:
      - name: clickhouse-keeper-local-config
        emptyDir: {}
      - name: clickhouse-readonly-config
        configMap:
          name: clickhouse-config-01
      containers:
      - name: clickhouse-keeper
        image: clickhouse/clickhouse-keeper:23.6
        ports:
        - containerPort: 9000
          name: tcp
        - containerPort: 9009
          name: tcp-metrics
        - containerPort: 9181
          name: zookeeper
        - containerPort: 9234
          name: raft
        command:
        - /bin/bash
        - -ecx
        - |
          clickhouse-keeper --config=/etc/clickhouse-keeper/keeper_config.xml
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -c
        #     - 'echo mntr | nc localhost 9181'
        #   initialDelaySeconds: 15
        volumeMounts:
        - name: clickhouse-keeper-local-config
          mountPath: /etc/clickhouse-keeper
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'cp  /tmp/keeper_config.xml /etc/clickhouse-keeper/' ]
        volumeMounts:
          - name: clickhouse-readonly-config
            mountPath: /tmp/
          - name: clickhouse-keeper-local-config
            mountPath: /etc/clickhouse-keeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-keeper-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-02
      role: keeper
  template:
    metadata:
      labels:
        app: clickhouse-02
        role: keeper
    spec:
      nodeSelector:
        kubernetes.io/hostname: n4
      volumes:
      - name: clickhouse-keeper-local-config
        emptyDir: {}
      - name: clickhouse-readonly-config
        configMap:
          name: clickhouse-config-01
      containers:
      - name: clickhouse-keeper
        image: clickhouse/clickhouse-keeper:23.6
        ports:
        - containerPort: 9000
          name: tcp
        - containerPort: 9009
          name: tcp-metrics
        - containerPort: 9181
          name: zookeeper
        - containerPort: 9234
          name: raft
        command:
        - /bin/bash
        - -ecx
        - |
          clickhouse-keeper --config=/etc/clickhouse-keeper/keeper_config.xml
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -c
        #     - 'echo mntr | nc localhost 9181'
        #   initialDelaySeconds: 15
        volumeMounts:
        - name: clickhouse-keeper-local-config
          mountPath: /etc/clickhouse-keeper
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'cp  /tmp/keeper_config.xml /etc/clickhouse-keeper/' ]
        volumeMounts:
          - name: clickhouse-readonly-config
            mountPath: /tmp/
          - name: clickhouse-keeper-local-config
            mountPath: /etc/clickhouse-keeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-keeper-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-03
      role: keeper
  template:
    metadata:
      labels:
        app: clickhouse-03
        role: keeper
    spec:
      nodeSelector:
        kubernetes.io/hostname: n4
      volumes:
      - name: clickhouse-keeper-local-config
        emptyDir: {}
      - name: clickhouse-readonly-config
        configMap:
          name: clickhouse-config-01
      containers:
      - name: clickhouse-keeper
        image: clickhouse/clickhouse-keeper:23.6
        ports:
        - containerPort: 9000
          name: tcp
        - containerPort: 9009
          name: tcp-metrics
        - containerPort: 9181
          name: zookeeper
        - containerPort: 9234
          name: raft
        command:
        - /bin/bash
        - -ecx
        - |
          clickhouse-keeper --config=/etc/clickhouse-keeper/keeper_config.xml
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -c
        #     - 'echo mntr | nc localhost 9181'
        #   initialDelaySeconds: 15
        volumeMounts:
        - name: clickhouse-keeper-local-config
          mountPath: /etc/clickhouse-keeper
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'cp  /tmp/keeper_config.xml /etc/clickhouse-keeper/keeper_config.xml' ]
        volumeMounts:
          - name: clickhouse-readonly-config
            mountPath: /tmp/
          - name: clickhouse-keeper-local-config
            mountPath: /etc/clickhouse-keeper