apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper-01
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: tcp
  - port: 9009
    name: tcp-metrics
  - port: 9181
    name: zookeeper
  - port: 9234
    name: raft
  selector:
    app: clickhouse-01
---
apiVersion: v1
kind: Service
metadata:
  name:  clickhouse-keeper-02
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: tcp
  - port: 9009
    name: tcp-metrics
  - port: 9181
    name: zookeeper
  - port: 9234
    name: raft
  selector:
    app: clickhouse-02
---
apiVersion: v1
kind: Service
metadata:
  name:  clickhouse-keeper-03
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: tcp
  - port: 9009
    name: tcp-metrics
  - port: 9181
    name: zookeeper
  - port: 9234
    name: raft
  selector:
    app: clickhouse-03
